function nodes = getNodesForBarWithComAzDec(com, azimuth, declination, length)
% Returns two nodes that represent the bar with the given configuration.
nodes = [ com(1) - length/2.0*sin(declination)*cos(azimuth), ...
          com(2) - length/2.0*sin(declination)*sin(azimuth), ...
          com(3) - length/2.0*cos(declination);
          com(1) + length/2.0*sin(declination)*cos(azimuth), ...
          com(2) + length/2.0*sin(declination)*sin(azimuth), ...
          com(3) + length/2.0*cos(declination)                  ];
end

